# Generated by Django 6.0.7 on 2026-07-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('mode', models.CharField(max_length=20)),
                ('advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=120)),
                ('resolved_name', models.CharField(blank=True, max_length=160)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('source', models.CharField(choices=[('openweather', 'OpenWeather'), ('demo', 'Demo fallback'), ('cache', 'Cache')], default='openweather', max_length=20)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
